# Generated by Django 5.2.14 on 2026-09-13 06:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('PROJECT_SITE', 'Project site'), ('TRANSIT', 'Transit')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('TRANSFER', 'Transfer'), ('ALLOCATION', 'Allocation'), ('RETURN', 'Return')], default='TRANSFER', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('dispatch_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('receive_idempotency_key', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers', to='companies.company')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.inventorylocation')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_inventory_transfers', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_inventory_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_inventory_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.inventorylocation')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('KG', 'Kilogram'), ('TON', 'Ton'), ('METER', 'Meter'), ('M2', 'Square meter'), ('M3', 'Cubic meter'), ('LITER', 'Liter'), ('BAG', 'Bag'), ('BOX', 'Box'), ('OTHER', 'Other')], max_length=16)),
                ('minimum_stock_level', models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_dispatched', models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_received', models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorytransfer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('ALLOCATE_OUT', 'Allocate out'), ('ALLOCATE_IN', 'Allocate in'), ('USE', 'Use'), ('RETURN_OUT', 'Return out'), ('RETURN_IN', 'Return in'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('signed_quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_transactions', to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_transactions', to='projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_material_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transaction', to='inventory.materialtransaction')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorytransfer')),
                ('transfer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorytransferitem')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['company', 'location_type', 'is_active'], name='inventory_i_company_14be2d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['company', 'project'], name='inventory_i_company_6b790d_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='inventory_location_company_name'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['company', 'status'], name='inventory_i_company_7f2bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['company', 'source_location'], name='inventory_i_company_338ff3_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_location', models.F('destination_location')), _negated=True), name='inventory_transfer_locations_differ'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['company', 'is_active'], name='inventory_m_company_ef4f19_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='inventory_material_company_code'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock_level__gte', 0)), name='inventory_material_minimum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'material'), name='inventory_transfer_one_material'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gte', 0), ('quantity_dispatched__gte', 0), ('quantity_received__gte', 0)), name='inventory_transfer_item_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'location'], name='inventory_i_company_bd3144_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'material'], name='inventory_i_company_6b539c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('company', 'material', 'location'), name='inventory_unique_balance'),
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['company', 'material', 'location'], name='inventory_m_company_f72abf_idx'),
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['company', 'project', 'occurred_at'], name='inventory_m_company_45b847_idx'),
        ),
        migrations.AddIndex(
            model_name='materialtransaction',
            index=models.Index(fields=['company', 'transaction_type'], name='inventory_m_company_906cff_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_transaction_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='materialtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='inventory_transaction_idempotency'),
        ),
    ]
