"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff } from "lucide-react";
import { api, setAccessToken } from "@/lib/api";
import { Button, Input, Alert, Label } from "@/components/ui";
import { useAuth } from "@/components/auth-provider";

export default function RegisterPage() {
  const router = useRouter(); const { refresh } = useAuth(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [show, setShow] = useState(false); const [show2, setShow2] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setPending(true); const form = new FormData(event.currentTarget); const pw = String(form.get("password")||""); const pw2 = String(form.get("password_confirm")||""); if (pw !== pw2) { setError("Passwords do not match."); setPending(false); return; } try { const result = await api<{access:string}>("/auth/register/", {method:"POST", body:JSON.stringify({first_name:form.get("first_name"),last_name:form.get("last_name"),email:form.get("email"),password:pw,password_confirm:pw2})}); setAccessToken(result.access); await refresh(); router.push("/settings?welcome=1"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create your account."); } finally { setPending(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#f6f5f0] p-4 sm:p-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-[#e5e8e3] bg-white p-6 sm:p-8 shadow-panel animate-fadeIn"><div className="mb-8"><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-moss font-bold text-white">B</div><h1 className="text-2xl font-bold tracking-tight">Start with clarity</h1><p className="mt-2 text-sm text-[#65716a]">Create your workspace — flexible for any screen.</p></div>{error && <Alert variant="error" className="mb-4">{error}</Alert>}<div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Label>First name<Input className="mt-1.5" name="first_name" required autoComplete="given-name" /></Label><Label>Last name<Input className="mt-1.5" name="last_name" autoComplete="family-name" /></Label></div><Label className="mt-4">Work email<Input className="mt-1.5" type="email" name="email" required placeholder="you@company.com" autoComplete="email" /></Label><Label className="mt-4">Password<div className="relative mt-1.5"><Input type={show ? "text" : "password"} name="password" minLength={10} required placeholder="Min 10 characters" autoComplete="new-password" className="pr-10" /><button type="button" onClick={() => setShow(!show)} className="absolute inset-y-0 right-0 grid w-10 place-items-center text-[#8a948e]">{show ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></Label><Label className="mt-4 mb-6">Confirm password<div className="relative mt-1.5"><Input type={show2 ? "text" : "password"} name="password_confirm" minLength={10} required placeholder="Repeat password" autoComplete="new-password" className="pr-10" /><button type="button" onClick={() => setShow2(!show2)} className="absolute inset-y-0 right-0 grid w-10 place-items-center text-[#8a948e]">{show2 ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></Label><Button className="w-full" size="lg" loading={pending}>{pending ? "Creating account…" : "Create account"}</Button><p className="mt-6 text-center text-sm text-[#65716a]">Already have an account? <Link className="font-semibold text-moss hover:underline" href="/login">Sign in</Link></p></form></main>;
}
