# Generated by Django 5.2.14 on 2026-09-13 06:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('currency_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('total_planned_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_budget_versions', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='budgets.budget')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_versions', to='companies.company')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_budget_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineage_key', models.UUIDField(default=uuid.uuid4)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_categories', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='budgets.budgetcategory')),
                ('budget_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='budgets.budgetversion')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_budgets', to='budgets.budgetversion'),
        ),
        migrations.AddIndex(
            model_name='budgetversion',
            index=models.Index(fields=['company', 'status'], name='budgets_bud_company_61bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetversion',
            index=models.Index(fields=['budget', 'status'], name='budgets_bud_budget__93f773_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('budget', 'version_number'), name='budget_unique_version_number'),
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.CheckConstraint(condition=models.Q(('total_planned_amount__gte', 0)), name='budget_version_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['company', 'budget_version'], name='budgets_bud_company_81e527_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('budget_version', 'code'), name='budget_category_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('budget_version', 'lineage_key'), name='budget_category_unique_lineage'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='budget_category_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['company', 'project'], name='budgets_bud_company_83bbe8_idx'),
        ),
    ]
