# Generated by Django 5.2.14 on 2026-09-13 07:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('work_completed', models.TextField(blank=True)),
                ('progress_delta', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('worker_count', models.PositiveIntegerField(default=0)),
                ('issues', models.TextField(blank=True)),
                ('weather_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_daily_revisions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_revisions', to='companies.company')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='reports.dailyreport')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_daily_revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportMaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('inventory_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('material_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_report_usage', to='inventory.materialtransaction')),
                ('daily_report_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_usages', to='reports.dailyreportrevision')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.FileField(upload_to='daily_report_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('daily_report_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='reports.dailyreportrevision')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='approved_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_reports', to='reports.dailyreportrevision'),
        ),
        migrations.AddIndex(
            model_name='dailyreportrevision',
            index=models.Index(fields=['company', 'status'], name='reports_dai_company_c2c830_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportrevision',
            constraint=models.UniqueConstraint(fields=('daily_report', 'revision_number'), name='reports_unique_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='dailyreportmaterialusage',
            constraint=models.UniqueConstraint(fields=('daily_report_revision', 'material', 'inventory_location'), name='reports_unique_usage'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_date'), name='reports_one_per_project_date'),
        ),
    ]
