# Generated by Django 5.2.14 on 2026-09-13 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('trade', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_on_project', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_assignments', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_assignments', to='projects.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workforce.worker')),
            ],
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['company', 'status'], name='workforce_w_company_89ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['company', 'trade'], name='workforce_w_company_99c007_idx'),
        ),
        migrations.AddIndex(
            model_name='workerassignment',
            index=models.Index(fields=['company', 'project', 'is_active'], name='workforce_w_company_3e1eb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('worker', 'project'), name='workforce_one_active_assignment'),
        ),
    ]
